name: Build docker container and run tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  
jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Build docker image
        run: docker build -t my-image -f Dockerfile.dev .

      - name: Run tests
        run: |
          docker run -e CI=true my-image npm run test

  build:
    needs: tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3
      
      - name: Build and push docker image
        run: |
          docker build -t my-image .
          docker push my-image
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    